- .gitignore
- deploy/group_vars/all.yml
- deploy/group_vars/k8s.yml
* Increase RDS volume size
* Define ``k8s_worker_celery_app`` variable
> [FJ-8] K8s tweaks to run first NC import

- .pre-commit-config.yaml
- pyproject.toml
- requirements/dev/dev.in
- requirements/dev/dev.txt
This just sets up the repo to run black. We should run black when we've got a stable develop.
> [FJ-13] Sets up .pre-commit

- .docker.env
- docker-compose.deploy.yml
- docker-compose.yml
- nc/data/importer.py
- nc/lookups.py
- nc/prime_cache.py
- nc/templates/nc/search.html
- nc/views.py
- requirements/base/base.in
- requirements/base/base.txt
- requirements/deploy/deploy.in
- requirements/deploy/deploy.txt
- requirements/dev/dev.txt
- requirements/test/test.txt
- traffic_stops/settings/base.py
- traffic_stops/settings/deploy.py
- traffic_stops/settings/dev.py
- tsdata/tests/test_utils.py
- tsdata/utils.py
https://caktus.atlassian.net/browse/FJ-29
* Use redis for all caching; remove flush_memcached
* Optionally use ``redis`` container during development to use cached responses (after priming)
* Remove stop counts on search pages for now (much faster querying) and was part of the reason caching wasn't working
* Increase PostgreSQL ``shm_size`` to mitigate no space left on device errors
> [FJ-29] Prime cache

- traffic_stops/settings/base.py
- traffic_stops/settings/deploy.py
This seems pretty straightforward.  Removed the duplicate assignment in deploy.
> [FJ-15] Re-targets the automated download dir.

- requirements/base/base.in
- requirements/base/base.txt
- requirements/dev/dev.txt
Doesn't really effect this setup.
> [FJ-30] bump Django

- traffic_stops/settings/deploy.py
https://caktus.atlassian.net/browse/FJ-40
> [FJ-40] Use default daily import schedule from base settings

- traffic_stops/static/js/app/states/nc/defaults.js
- traffic_stops/static/less/index.less
change chart colors and black-block colors
> [FJ-39] color changes

- traffic_stops/settings/base.py
- Sets up master and fixes email bug
> Production deploy 2020-09-29

- deploy/group_vars/all.yml
Increase RDS volume to 100GB. This has already been applied on production.
> [FJ-26] Increase RDS volume to 100GB

- nc/data/importer.py
Filters out files that have recently popped up in the import zip.
> [FJ-58] Filters out new files breaking import

- frontend/public/index.html
> [FJ-80] adds gtm

- nc/data/NC_agencies.csv
* Set new agency IDs in stone so they don't change from import to import
* Stop receiving the email notification
Hot fix for `master`. Also needs to be committed to `develop`.
> [FJ-46] Add new discovered agencies (hotfix)

- .dockerignore
- frontend/src/Components/AgencyData/AgencyHeader.js
- nc/serializers.py
- traffic_stops/settings/deploy.py
- traffic_stops/templates/index.html
* Add `last_reported_stop` to agency detail API endpoint
* Format `agencyDetails.last_reported_stop` date
* Also add `index.html` to project templates to avoid 404s during local development
> [FJ-90] Display last reported stop

- nc/serializers.py
- nc/tests/api/conftest.py
- nc/tests/api/test_state_facts.py
- nc/urls.py
- nc/views.py
API for state facts used on the home page.
> [FJ-21] State facts API

- frontend/src/Components/AboutPage/AboutPage.js
- frontend/src/Components/AboutPage/AboutPage.styled.js
> [FJ-101] about page, responsive

- frontend/src/Components/AgencyList/AgencyList.js
- frontend/src/Components/AgencyList/AgencyList.styled.js
style agency list, minus list of letters...
> [FJ-61] Agency List page

- frontend/package-lock.json
- frontend/package.json
- frontend/src/Components/Elements/DepartmentSearch.js
bump reaktus and add tabindex for fix,
> [FJ-67] View All Departments bug

- frontend/src/Components/AgencyData/AgencyData.styled.js
- frontend/src/Components/AgencyData/AgencyHeader.js
- frontend/src/Components/AgencyData/AgencyHeader.styled.js
- frontend/src/Components/Charts/ChartPrimitives/Pie.js
- frontend/src/Components/Charts/ChartSections/ChartsCommon.styled.js
- frontend/src/Components/Charts/ChartSections/DataSubsetPicker/DataSubsetPicker.js
- frontend/src/Components/Charts/Contraband/Contraband.js
- frontend/src/Components/Charts/Overview/Overview.js
- frontend/src/Components/Charts/SearchRate/SearchRate.js
- frontend/src/Components/Charts/Searches/Searches.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/Charts/UseOfForce/UseOfForce.js
- frontend/src/Components/Elements/Dropdown/Dropdown.js
- frontend/src/Components/Elements/Dropdown/Dropdown.styled.js
Resolves all them bugs. Except 105. There's a year dropdown in the Overview section, but not all of those charts support yearly breakdowns. There would have to be a year dropdown per-chart, which wouldn't look great. Punting for now. It'll need a design if it's a wanted feature.
> [FJ-102/103/104/105] some bugs

- deploy/requirements.yml
- requirements/dev/dev.in
- requirements/dev/dev.txt
> [TSC-162] Bump Invoke and Django-K8s

- frontend/src/Components/Charts/Overview/Overview.js
explicitly set empty data for no census in census pie
> [FJ-113] Census Data Bleeding

- frontend/src/Components/Charts/ChartPrimitives/Line.js
- frontend/src/Components/Charts/SearchRate/SearchRate.js
- frontend/src/Components/Charts/Searches/Searches.js
adds labels and formats ticks to:
- Searches by Percentage
- Search Rate
> [FJ-120] improve chart labels

- frontend/src/Components/FindAStopPage/FindAStopPage.styled.js
adds a lil' z-index to the datepicker
> [FJ-119] DatePicker zIndex issue

- frontend/package-lock.json
- frontend/package.json
- frontend/src/Components/Elements/DepartmentSearch.js
- frontend/src/Components/Elements/Inputs/AutoSuggest.js
- frontend/src/Components/Header/HeaderSearch.js
update reaktus for static dropdown height
set a responsive height to dropdown
> [FJ-118] Agency Search Off screen on Mobile

- frontend/src/Components/HomePage/HomePage.styled.js
- frontend/src/styles/StyledComponents/FullWidthPage.styled.js
> [FJ-122] Homepage Scroll Issues

- frontend/src/Components/AgencyData/AgencyHeader.styled.js
- frontend/src/Components/Charts/ChartSections/ChartPageBase.styled.js
Reduces padding on agency header elements
I think this is the best we can get here in the time we have. There's just not a lot of wiggle room, given the designs we've got.
> [FJ-123] Agency Header Size Issue

- frontend/src/Components/Charts/ChartPrimitives/Bar.js
- frontend/src/Components/Charts/ChartPrimitives/GroupedBar.js
- frontend/src/Components/Charts/ChartPrimitives/Line.js
- frontend/src/Components/Charts/ChartPrimitives/Pie.js
- frontend/src/Components/Charts/ChartPrimitives/StackedBar.js
Add VictoryContainer with touchAction 'auto' to propagate touch events
> [FJ-117] Chart Page Mobile Scrolling

- frontend/src/Components/Charts/ChartSections/Legend/Legend.js
- frontend/src/Components/Charts/ChartSections/Legend/Legend.styled.js
Removes hover state from pie keys.
> [FJ-114] Pie Chart Legend Keys

- frontend/src/Components/AboutPage/AboutPage.styled.js
- frontend/src/Components/AgencyList/AgencyList.styled.js
- frontend/src/Components/Charts/ChartSections/ChartPageBase.js
- frontend/src/Components/Charts/ChartSections/ChartPageBase.styled.js
- frontend/src/Components/FindAStopPage/FindAStopPage.js
- frontend/src/Components/FindAStopPage/FindAStopPage.styled.js
- frontend/src/Components/FindAStopPage/FindAStopResults.js
- frontend/src/Components/FindAStopPage/FindAStopResults.styled.js
- frontend/src/Components/Footer/Footer.js
- frontend/src/Components/Footer/Footer.styled.js
- frontend/src/Components/HomePage/HomePage.js
- frontend/src/Components/HomePage/HomePage.styled.js
- frontend/src/styles/StyledComponents/FullWidthPage.js
Accidentally committed to previous feature branch, but since we're just cranking through these and FJ-114 is small, it ought not be an issue.
This PR creates a Footer and adds it to base templates where applicable. A bit of reworking was necessary where page layout hand't intended to accommodate a footer.  For what it's worth, I didn't include the footer from the mockups because it seemed like a stub. There's not content for it, so it doesn't strike me as all that valuable. I can appreciate how it helps users understand the layout a bit, but that doesn't feel like much of a win.
> [FJ-106] Add footer to base pages, or create base pages

- nc/data/importer.py
https://caktus.atlassian.net/browse/FJ-121
> [FJ-121] set cursor timezone back to UTC

- frontend/src/Components/AgencyData/AgencyHeader.js
- frontend/src/Components/AgencyData/AgencyHeader.styled.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/FindAStopPage/FindAStopResults.js
- frontend/src/Components/FindAStopPage/FindAStopResults.styled.js
- frontend/src/Components/Footer/Footer.js
- frontend/src/Components/Footer/Footer.styled.js
- frontend/src/Components/Header/Header.js
- frontend/src/Components/Header/Header.styled.js
See [this basecamp post](https://3.basecamp.com/3120230/buckets/18119898/messages/3605027601)  for targeted fixes.
> FJ  Final pre-deploy fixes

- frontend/src/Components/Charts/ChartSections/Legend/Legend.js
- frontend/src/Components/Charts/SearchRate/SearchRate.js
- frontend/src/Components/Charts/Searches/Searches.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
Removes non-hispanic asterisks from "Hispanic" label
> #10729 -- Remove non-hispanic asterisks from "Hispanic" label

- frontend/src/Components/Charts/SearchRate/SearchRate.js
- frontend/src/Components/Charts/chartUtils.js
- frontend/src/Components/Elements/Table/TableModal.js
- frontend/src/Hooks/useDataset.js
- frontend/src/Services/endpoints.js
- Simplified data to show just searches, since the data was similar to traffic count.
- Sorted the data by descending year
- Added a total row for each race.
- Added a dropdown filter for stop purpose
Preview:
Closes #14088
> Resolve: 14088 View Data: Likelihood of search

- frontend/src/Components/Elements/Table/TableModal.js
- Update table data in modals to match sorting and maintain consistency across tables
- Make sure all tables have a total row.
> Resolve: Update remaining table data

- frontend/src/Components/Sidebar/Sidebar.js
- Update sidebar copy to reflect correct type of data shown, department vs. officer.
Preview:
Closes #14907
> Resolve: 14907 Switch "Department Data" to say "Officer Data" on left hand search bar menu

- frontend/src/Components/Charts/ChartPrimitives/Bar.js
- frontend/src/Components/Charts/ChartPrimitives/GroupedBar.js
- frontend/src/Components/Charts/ChartPrimitives/Line.js
- frontend/src/Components/Charts/ChartPrimitives/StackedBar.js
- frontend/src/Components/Charts/ChartSections/ChartsCommon.styled.js
- frontend/src/Components/Charts/ChartSections/EmptyChartMessage.js
Add new component to appear when data is not available for charts. 
Updated various chart components to include message if data is not available. 
Preview:
> Resolve: 14247 Message for missing data

- deploy/group_vars/all.yml
- deploy/group_vars/k8s.yml
- deploy/requirements.yml
Reverts caktus/Traffic-Stops#108
> Revert "Q2 2022 Kubernetes Upgrades"

- deploy/group_vars/all.yml
- deploy/group_vars/k8s.yml
- deploy/requirements.yml
Upgraded ingress and cert manager to latest version.
> Q2 2022 Kubernetes Upgrades

- .github/workflows/deploy.yaml
- requirements/dev/dev.in
- requirements/dev/dev.txt
- #112 
I had trouble finding compatible versions for everything, but afaict, Jinja was the culprit:
```diff
-jinja2==2.11.2
+jinja2==3.0.3
```
> [112] Deploy fix

- frontend/src/Components/Charts/Overview/Overview.js
- Update copy of Use of Force pie chart in Overview page to reflect officer vs department page. 
Preview:
Department
Officer
Closes #15745
> Resolve: 15745 Update copy for officer/department use force pie chart

- frontend/src/Components/AboutPage/AboutPage.js
- frontend/src/styles/StyledComponents/FullWidthPage.styled.js
- Removed box shadow from contact submit button
- Removed scrollbar in the middle of the page. 
Preview:
> Fix small ui bugs

- frontend/src/Components/Elements/Table/TableModal.js
- Update modal headers to match charts
Closes #14089
> Resolve: 14089 Update header for the Searches by count graph.

- frontend/src/Components/AboutPage/AboutPage.js
- frontend/src/Components/Elements/Table/TableModal.js
- Fix which data is shown in modal table to align with chart data.
> Modal table data discrepancy fix

- nc/views.py
- Sort stop dates descending order
Preview:
Closes #10306
> Resolve: 10306 Order find a stop search results by recent dates. 

- frontend/src/Components/Elements/BackButton.styled.js
- frontend/src/Components/Elements/Inputs/Input.styled.js
- frontend/src/Components/Elements/Table/TablePagination.styled.js
- Certain elements that are clickable weren't known to the user since the cursor was not a 'pointer'.
Closes: #10308
> Resolve: 10308 Add hover states to elements

- frontend/src/Components/Charts/ChartSections/ChartHeader.js
- frontend/src/Components/Charts/ChartSections/ShareList.js
- Cleanup social share button logic to show icons 
Preview:
Closes: #16006
> Resolve: 16006 - Fix broken share button

- frontend/src/Components/AgencyData/AgencyData.js
- frontend/src/Components/AgencyData/AgencyData.styled.js
- frontend/src/Components/AgencyData/AgencyHeader.js
- frontend/src/Components/App.js
- frontend/src/Components/App.styled.js
- frontend/src/Components/Charts/ChartRoutes.js
- frontend/src/Components/Charts/ChartSections/ChartHeader.styled.js
- frontend/src/Components/Charts/ChartSections/ChartsCommon.styled.js
- frontend/src/Components/Charts/Contraband/Contraband.js
- frontend/src/Components/Charts/Overview/Overview.js
- frontend/src/Components/Charts/SearchRate/SearchRate.js
- frontend/src/Components/Charts/Searches/Searches.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/Charts/UseOfForce/UseOfForce.js
- frontend/src/Components/Layout.styled.js
- frontend/src/Context/chart-reducer.js
- frontend/src/Hooks/useDataset.js
- Update `ChartRoutes.js` to pass `agencyId` and `showCompare` props to chart components
- Update `App.js` to show/hide second `AgencyData` component if user wishes to compare
- Cleanup css to show 2 agency data info at same time without obstructing any graphs.
Preview:
Closes #16095
> Resolve: 16095 Comparison tool

- frontend/src/Components/Elements/Inputs/Input.js
- Add ref to FJ Input so the icon associated with it can trigger then focus event. 
- This provides users with a better ux.
> Bug fix for #10308

- frontend/src/Components/AgencyData/AgencyHeader.js
- frontend/src/Components/AgencyData/AgencyHeader.styled.js
- The compare feature on mobile screens looks a bit cramped. For now, hide the option. 
Preview:
> On mobile, for now, hide option to compare departments

- frontend/src/Hooks/useYearSet.js
- When consolidating data in table modal, the current year was missing. 
Preview:
> Add 1 more year to include in range

- frontend/src/Components/AgencyData/AgencyData.js
- frontend/src/Components/AgencyData/AgencyData.styled.js
- frontend/src/Components/App.js
- frontend/src/Components/Charts/ChartSections/ChartsCommon.styled.js
- frontend/src/Components/Elements/Dropdown/Dropdown.styled.js
- frontend/src/styles/MainBase.js
Finally found out a better way to do this with CSS instead of hooking into React refs.
> Improve scroll when comparing agencies

- frontend/src/Components/Charts/Contraband/Contraband.js
- frontend/src/Components/Charts/Overview/Overview.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- If someone had selected a year and that agency had no data for it, the page would crash. Hopefully not anymore.
> Bug fix no data for selected year

- frontend/src/Components/Charts/Contraband/Contraband.js
- frontend/src/Components/Charts/Overview/Overview.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
Reverts caktus/Traffic-Stops#149
> Revert "Bug fix no data for selected year"

- frontend/src/Components/Charts/Contraband/Contraband.js
- frontend/src/Components/Charts/Overview/Overview.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
Trying https://github.com/caktus/Traffic-Stops/pull/149
> Retrying #149

- frontend/src/Components/Charts/ChartSections/DataSubsetPicker/DataSubsetPicker.js
- frontend/src/Components/Charts/Overview/Overview.js
- frontend/src/Components/Elements/Dropdown/Dropdown.js
- frontend/src/Components/Elements/Dropdown/Dropdown.styled.js
- When in mobile view, the year dropdown was cutoff from the top. Here we force it always down.
> Fix dropdown cutoff overview page in mobile view

- frontend/src/Components/AgencyData/AgencyHeader.styled.js
- frontend/src/Components/Charts/ChartSections/ChartHeader.styled.js
- frontend/src/Components/Charts/ChartSections/ChartPageBase.styled.js
- frontend/src/Components/Charts/ChartSections/ChartsCommon.styled.js
- frontend/src/Components/Charts/ChartSections/Legend/Legend.styled.js
- frontend/src/Components/Sidebar/Sidebar.js
- frontend/src/Components/Sidebar/SidebarLink.js
- frontend/src/Components/Sidebar/SidebarLink.styled.js
Mostly update to accommodate small screen sizes when comparing agencies.
> Update stylings for mobile

- Makefile
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/Charts/chartUtils.js
- frontend/src/Components/Elements/Table/Table.js
- frontend/src/Components/Elements/Table/Table.styled.js
- frontend/src/Components/Elements/Table/TableModal.js
- Indicate of no data has been recored for given year
Preview:
> Show message if no data is recorded for row

- frontend/src/Components/AgencyData/AgencyHeader.styled.js
> Show compare button on mobile

- .gitignore
- docs/census.rst
- nc/admin.py
- nc/data/NC_agencies.csv
- requirements/base/base.in
- requirements/base/base.txt
- traffic_stops/settings/base.py
- tsdata/acs.py
- tsdata/management/commands/import_census.py
- tsdata/models.py
- https://app.clickup.com/t/3xkt5hd
1. Download and import latest `acs-2018.json` file:
```sh
python manage.py import_census
```
2. Visit http://localhost:8000/admin/nc/agency/-1/change/ fill in **0400000US37** for the Census Profile ID. Add Last Reported Stop if empty.
3. View the state dashboard: http://localhost:8000/agencies/-1
> Update to include NC state facts

- nc/serializers.py
- Updates the resources serializer to get the first resource, if available, to use for the view more button if there isn't an intentional value for the view more link.
> Use first resource link in place of empty view more link

- frontend/src/Components/Elements/Table/TableModal.js
- nc/views.py
- https://app.clickup.com/t/863gpf59w
- https://app.clickup.com/t/863gq35h9
- Reset the start/end dates for the range picker after the modal is closed
- Update contraband mapping function to use the state's yearRange instead of the component's year range value, was flaky with the table data updating
> Bug fix: Contraband table not filtering years using date range

- frontend/src/util/tooltipLanguage.js
> Update average tooltip language

- deploy/group_vars/k8s.yml
- https://app.clickup.com/t/863gtve1c
> Increase migration timeout to 5 minutes

- frontend/src/Components/Charts/Searches/Searches.js
- frontend/src/util/displayDefinition.js
Ticket:
- https://app.clickup.com/t/867829bc7
What Changed:
- Added definitions under the search type dropdown to display a what that selected search type means. 
Preview:
> Add search type definitions under the dropdown

- frontend/src/Components/Elements/Table/TableModal.js
- Forgot to add the officer id if found in the url to the modal fetch request
> Hotfix officer data in modals is incorrect

- nc/views.py
- A `KeyError` would raise if a race wasn't found in the pandas dataframe for the grouped stop purpose graph, this fix returns a list of 0's of length # of years available.
> Prevent key error when fetching values for each race

- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/NewCharts/LineChart.js
- frontend/src/util/tooltipLanguage.js
Added in some logic to show and hide a custom tooltip when hovering over the legend items in the traffic stops by stop purpose graph. 
Preview:
> Adding tooltips to chart legends

- frontend/src/Components/App.js
- frontend/src/Components/Charts/ChartSections/ChartsCommon.styled.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/NewCharts/ChartModal.js
- frontend/src/Components/NewCharts/ChartModal.styled.js
- frontend/src/Components/NewCharts/PieChart.js
Ticket:
- https://app.clickup.com/t/86853neq0
- Adds modal for individual charts to view more data and download a png copy.
Preview:
> Add chart modal to download individual charts

- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/Elements/Table/TableModal.js
- frontend/src/Components/NewCharts/LineChart.js
- nc/urls.py
- nc/views.py
- Fixes small bugs found during testing
> Several bug fixes

- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/Elements/MonthRangePicker.js
- frontend/src/Components/NewCharts/PieChart.js
- nc/views.py
Tickets:
- https://app.clickup.com/t/86859jnrv
- Default pie charts to 0 
- Add minYear and maxYear for the range picker in graphs, only show available years from the db.
> Fix pie charts without data + limit range pickers for graphs

- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/util/tooltipLanguage.js
- Fixes the language for the tooltip grouped stop purposes, moving seat belt into regulatory
- Fixes placement of legend for tooltips
Preview:
> Update tooltip language and placement

- Dockerfile
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.styled.js
- frontend/src/Components/Elements/Table/TableModal.js
- frontend/src/Components/NewCharts/LineChart.js
- frontend/src/Components/NewCharts/PieChart.js
- frontend/src/util/tooltipLanguage.js
- nc/prime_cache.py
- nc/urls.py
- nc/views.py
**Do not use squash and merge**
* No new features added
* Update caching to include new traffic endpoints (https://github.com/caktus/Traffic-Stops/pull/228)
* Update tooltip language (https://github.com/caktus/Traffic-Stops/pull/229)
* Update pie chart tooltip UI (https://github.com/caktus/Traffic-Stops/pull/230)
* Upgrade node version to LTS 18.17.0 (https://github.com/caktus/Traffic-Stops/pull/231)
> Prepare production release v1.11.0 #227

- frontend/src/Components/AgencyData/AgencyHeader.js
- frontend/src/Components/AgencyData/AgencyHeader.styled.js
- frontend/src/Components/AgencyData/CensusData.js
- frontend/src/Components/AgencyList/AgencyList.js
- frontend/src/Components/AgencyList/AgencyList.styled.js
- frontend/src/Components/Charts/ChartSections/ChartsCommon.styled.js
- frontend/src/Components/Charts/ChartSections/Legend/Legend.js
- frontend/src/Components/Charts/ChartSections/Legend/Legend.styled.js
- frontend/src/Components/Charts/Contraband/Contraband.js
- frontend/src/Components/Charts/Overview/Overview.js
- frontend/src/Components/Charts/SearchRate/SearchRate.js
- frontend/src/Components/Charts/Searches/Searches.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.styled.js
- frontend/src/Components/Charts/UseOfForce/UseOfForce.js
- frontend/src/Components/Elements/DepartmentSearch.js
- frontend/src/Components/Elements/Dropdown/Dropdown.js
- frontend/src/Components/NewCharts/ChartModal.js
- frontend/src/Hooks/useYearSet.js
Bugs addressed in this ticket description: https://app.clickup.com/t/8685pnqd1
> Various bug fixes from site walkthrough with client.

- frontend/src/Components/Charts/ChartSections/Legend/Legend.js
- frontend/src/Components/Charts/Contraband/Contraband.js
- frontend/src/Components/Charts/chartUtils.js
- frontend/src/Components/NewCharts/HorizontalBarChart.js
- frontend/src/styles/themes.styled.js
- nc/urls.py
- nc/views.py
> Add new Hit Rate By Type chart to the contraband tab

- frontend/src/Components/Charts/Overview/Overview.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/Charts/UseOfForce/UseOfForce.js
- frontend/src/Components/NewCharts/PieChart.js
- frontend/src/util/getDownloadableTitle.js
- frontend/src/util/setChartColors.js
Tickets:
- https://app.clickup.com/t/8686edcp4
- https://app.clickup.com/t/8686eddm1
- Moved new chart modal into pie chart component for re-use
- Update Overview, Traffic Stops and Use of Force pie charts to use new library/component and view more modal
Preview:
> Update other pie charts across the site to use the new chart library

- frontend/src/Components/Charts/Overview/Overview.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/Charts/UseOfForce/UseOfForce.js
- frontend/src/Components/NewCharts/PieChart.js
- frontend/src/util/getDownloadableTitle.js
- frontend/src/util/setChartColors.js
**Do not use squash and merge**
* Update pie charts across the site to use the new chart library https://github.com/caktus/Traffic-Stops/pull/249
* No bug fix added
* No upgrades were made
> Production release v1.15.0

- frontend/src/Components/Charts/Contraband/Contraband.js
- frontend/src/Components/Charts/Overview/Overview.js
- frontend/src/Components/Charts/Searches/Searches.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/Charts/UseOfForce/UseOfForce.js
- frontend/src/Components/NewCharts/ChartModal.js
- frontend/src/Components/NewCharts/ChartModal.styled.js
- frontend/src/Components/NewCharts/HorizontalBarChart.js
- frontend/src/Components/NewCharts/LineChart.js
- frontend/src/Components/NewCharts/PieChart.js
- nc/urls.py
- nc/views.py
Ticket:
- https://app.clickup.com/t/8686n7xdt
- Add chart modal + downloadable logic for line charts similar to pie charts
Preview:
> Update new line charts to expand and download charts

- frontend/src/Components/Charts/Contraband/Contraband.js
> Update contraband grouped by stop purpose colors

- frontend/src/Components/Charts/Contraband/Contraband.js
- frontend/src/Components/Charts/Overview/Overview.js
- frontend/src/Components/Charts/Searches/Searches.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/Charts/UseOfForce/UseOfForce.js
- frontend/src/Components/Charts/chartUtils.js
- frontend/src/Components/NewCharts/ChartModal.js
- frontend/src/Components/NewCharts/ChartModal.styled.js
- frontend/src/Components/NewCharts/HorizontalBarChart.js
- frontend/src/Components/NewCharts/LineChart.js
- frontend/src/Components/NewCharts/PieChart.js
- frontend/src/Components/NewCharts/VerticalBarChart.js
- nc/prime_cache.py
- nc/urls.py
- nc/views.py
**Do not use squash and merge**
* Update traffic stop, search graphs to use the new chart library (https://github.com/caktus/Traffic-Stops/pull/252)
* Update contraband colors and cache url list (https://github.com/caktus/Traffic-Stops/pull/254, https://github.com/caktus/Traffic-Stops/pull/257)
* Update use of force graph to use new chart library (https://github.com/caktus/Traffic-Stops/pull/255)
* Update traffic stops by percentage (https://github.com/caktus/Traffic-Stops/pull/256)
* No bug fix added
* No upgrades were made
> Production release v1.16.0

- frontend/src/Components/Charts/Contraband/Contraband.js
- frontend/src/Components/Charts/Overview/Overview.js
- frontend/src/Components/Charts/SearchRate/SearchRate.js
- frontend/src/Components/Charts/Searches/Searches.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/Charts/UseOfForce/UseOfForce.js
- frontend/src/Components/NewCharts/HorizontalBarChart.js
- frontend/src/Components/NewCharts/LineChart.js
- frontend/src/Components/NewCharts/PieChart.js
- frontend/src/Components/NewCharts/VerticalBarChart.js
- nc/views.py
- Fixed several Sentry error bugs that crashed site if a DataFrame key was missing (i.e. `Native American`)
- Updated new graphs to use a `loading` state variable to distinguish between fetching still in progress and data returned with empty values.
> Fix KeyError bugs

- frontend/src/Components/Charts/ChartSections/EmptyChartMessage.js
- frontend/src/Components/Charts/Contraband/Contraband.js
- frontend/src/Components/Charts/Overview/Overview.js
- frontend/src/Components/Charts/SearchRate/SearchRate.js
- frontend/src/Components/Charts/Searches/Searches.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- frontend/src/Components/Charts/UseOfForce/UseOfForce.js
- frontend/src/Components/NewCharts/HorizontalBarChart.js
- frontend/src/Components/NewCharts/LineChart.js
- frontend/src/Components/NewCharts/VerticalBarChart.js
Tickets:
- https://app.clickup.com/t/8686mazbw
- https://app.clickup.com/t/3xkt6ny
- Updated descriptions when viewing statewide to not say department or officer
- Update the last contraband graph y axis values
- Fix the table data crashing the frontend if no data is returned from the api request
- Include the missing data component to the new charts so the user isn't kept guessing if the data has been returned or not
> Fix various bugs

- frontend/src/Components/Charts/ChartSections/ShareList.js
- frontend/src/Components/Charts/Contraband/Contraband.js
- frontend/src/Components/Charts/Searches/Searches.js
- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- Update share links to include an anchor tag for pages with multiple graphs that way it can scroll on page load to the specific graph shared.
> Scroll page to shared graph

- frontend/src/Components/Charts/Overview/Overview.js
- Update overview page to call years range from util func instead of context state
> Fix dropdown year bug

- frontend/src/Components/Charts/TrafficStops/TrafficStops.js
- Added pie chart for Traffic Stops by Stop Purpose
- Fix dropdown bug for traffic stops by percentage
Preview:
> Add pie chart for Traffic Stops by Stop Purpose

- deploy/deploy-cf-stack.yml
- deploy/group_vars/all.yml
The CF ChangeSet has already been executed
> Reduce DatabaseBackupRetentionDays from 30 to 2 days

- .devcontainer/devcontainer.json
- .github/workflows/deploy.yaml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- Dockerfile
- docs/dev-setup.rst
This Pull Request updates Python from 3.10 to 3.12.
Closes:
- https://app.clickup.com/t/868byg3q6
> Upgrade Python Version v3.10 -> v3.12

- nc/tests/api/test_arrests.py
- nc/views/likelihood.py
- nc/views/main.py
Updates Dataframe assignments to use Python 3.x-safe syntax.
* Click around on chart links for an agency
* Verify no Pandas upgrade warnings are displayed in console
> Fix the pandas ChainedAssignmentError warning
