nc/templates/nc.html, nc/templates/nc/agency_detail.html, requirements/base/base.in, requirements/base/base.txt, requirements/deploy/deploy.txt, requirements/dev/dev.txt, traffic_stops/templates/agency_detail.html, traffic_stops/templates/agency_list.html, traffic_stops/templates/base.html, traffic_stops/templates/home.html, traffic_stops/templates/includes/navigation.html, traffic_stops/templates/state.html
This was branched off of FJ-5, so that will need to be merged first. Changes `{% load staticfiles %}` to `{% load static %}` in advance of 3.0 deprecation.
=> Fj 7/what is left to fix

package-lock.json, package.json
necessary to upgrade watchify package in order to upgrade fsevents to non-breaking version for macos
=> upgrade watchify for fsevents upgrade

nc/templates/nc/agency_detail.html
adds opengraph meta tags to agency_detail for testing
This isn't the final PR, but it does need to go to staging to test. 
Also, there's a bit of a problem with testing it. We'll need to disable basic auth so that we can test the OG elements in social media.
=> [FJ-41] Simple Social Share

nc/templates/nc/agency_detail.html, tsdata/acs.py, tsdata/management/commands/import_census.py
https://caktus.atlassian.net/browse/FJ-20
Turns out the Python library supports 2018 data, so the update was pretty straightforward:
* Use 2018 5-Year ACS data
* Upload compiled JSON data to S3 bucket
* Update census display to use new row formatting 
To test, run:
* ``python manage.py import_census``
* Confirm census data is on Durham agency page: http://localhost:8000/agency/80/
* Confirm Durham data matches [2018 ACS 5-Year data on data.census.gov](https://data.census.gov/cedsci/table?g=1600000US3719000&d=ACS%205-Year%20Estimates%20Data%20Profiles&tid=ACSDP5Y2018.DP05&moe=false&tp=false&hidePreview=true):
* HISPANIC OR LATINO AND RACE -> Total population
* Not Hispanic or Latino
* **White**
* **Black**
* **Native America**
* **Asian**
* **Other** (combination of Native Hawaiian, Some …
=> [FJ-20] 2018 5-Year ACS Data

nc/data/copy_nc.py, nc/data/importer.py
https://caktus.atlassian.net/browse/FJ-46
This update fixes an import bug (during our refactor late last year, I believe) that prevented agency loading when **no new agencies** were discovered in the data file. In this case, rather than pointing to an importer-generated file `<import location>/NC_agencies.csv`, the existing file in `nc/data/NC_agencies.csv` should be referenced.
I've tested this locally using both import methods and confirmed it's working.
=> [FJ-46] Copy agencies in using correct file during import

nc/data/timezones.ipynb, nc/serializers.py, nc/tests/api/test_basic_search.py, nc/tests/api/test_timezones.py, traffic_stops/settings/base.py
https://caktus.atlassian.net/browse/FJ-100
The bug was that since the default `TIME_ZONE` was `UTC`, the API would parse `stop_date` as `UTC` and filter stops using this time zone.
So, for example, if the frontend client requests `{stop_date_after: "2020-08-01"}`:
* The API constructs a datetime as `UTC`:
* `datetime.datetime(2020, 8, 1, 0, 0, tzinfo=<UTC>)`
* This datetime represented in `America/New_York` is:
* `datetime.datetime(2020, 7, 31, 20, 0, tzinfo=<DstTzInfo 'America/New_York' EDT-1 day, 20:00:00 DST>)`
* So when filtering Stops by date, which are stored as offsets from UTC, results from July 31st 8p ET (aka 8/1 12p UTC) and later are returned.
Setting `TIME_ZONE = "America/New_York"` makes the most sense since only NC stops are included now on NC CopWatch and guarantees the …
=> [FJ-100] Filter NC stops using NC timezone

README.rst, docs/deploy.rst
Per [SEC-174](https://caktus.atlassian.net/browse/SEC-174), update reference to IAM role in docs to match [aws-assumerole](https://github.com/caktus/caktus-hosting-services/blob/main/docs/aws-assumerole.md#aws-accounts)
=> [SEC-174] Point to proper IAM role name

frontend/src/Components/Charts/ChartPrimitives/Bar.js, frontend/src/Components/Charts/ChartPrimitives/ChartBase.js, frontend/src/Components/Charts/ChartPrimitives/ChartLoading.js, frontend/src/Components/Charts/ChartPrimitives/DataLoading.js, frontend/src/Components/Charts/ChartPrimitives/DataLoading.styled.js, frontend/src/Components/Charts/ChartPrimitives/GroupedBar.js, frontend/src/Components/Charts/ChartPrimitives/Line.js, frontend/src/Components/Charts/ChartPrimitives/Pie.js, frontend/src/Components/Charts/ChartPrimitives/StackedBar.js, frontend/src/Components/Charts/ChartRoutes.js, frontend/src/Components/Charts/ChartSections/ChartPageBase.styled.js, frontend/src/Components/Elements/Skeletons/BarSkeleton.js, frontend/src/Components/Elements/Skeletons/PieSkeleton.js
Makes the loading skeletons a bit larger and adds "Loading {agency | officer} data..." text to make loading states more obvious. Added it to both the bundle loading and the chart data loading.
You can test this locally or on staging by loading a chart page. If it loads too quickly to see the loading indicators, use dev tools Network tab to throttle your connection (probably "slow 3g" is good).
=> [FJ-136] More prominent loading

frontend/src/Components/Charts/ChartSections/ChartPageBase.styled.js
Adds static height to the `<article>` containing the charts section, so that `overflow-y: auto` is respected.
=> [FJ-137] AgencyDetail scroll issue

frontend/src/Components/AgencyData/AgencyHeader.js, frontend/src/Components/Charts/Overview/Overview.js
There was one more misleading asterisk next to "Hispanic" in the census demographics header. It has been removed.
=> Remove one more asterisk

frontend/src/Components/Charts/ChartPrimitives/CopwatchChart.js, frontend/src/Components/Charts/ChartPrimitives/CopwatchChart.styled.js, frontend/src/Components/Charts/ChartPrimitives/GroupedBar.js, frontend/src/Components/Charts/ChartPrimitives/Line.js, frontend/src/Components/Charts/ChartPrimitives/Pie.js, frontend/src/Components/Charts/ChartPrimitives/StackedBar.js, frontend/src/Components/Charts/SearchRate/SearchRate.js, frontend/src/Components/Charts/Searches/Searches.js, frontend/src/Components/Charts/TrafficStops/TrafficStops.js, frontend/src/Components/Charts/UseOfForce/UseOfForce.js, frontend/src/Components/Charts/chartUtils.js
All charts (except maybe one that was deemed redundant) now have a "tooltip" when you hover over data points.  In some cases it's 1:1-- the data point you hover over is expanded into a tooltip. In other cases, a voronoi is used to calculate the closest intersection of corresponding data points on the dependent axis and all data points are displayed in the tooltip for that point on the x-axis. It makes more sense when you just look at it.
There were a few changes that seemed to have effective performance a bit, so it makes some sense to put these changes to a bit of a stress test both locally and on staging.
=> [#11498] Add tooltips to charts

frontend/src/Components/Charts/ChartPrimitives/CopwatchChart.js, frontend/src/Components/Charts/ChartPrimitives/CopwatchChart.styled.js, frontend/src/Components/Charts/ChartPrimitives/GroupedBar.js, frontend/src/Components/Charts/ChartPrimitives/Line.js, frontend/src/Components/Charts/ChartPrimitives/StackedBar.js, frontend/src/Components/Charts/Searches/Searches.js, frontend/src/Components/Charts/TrafficStops/TrafficStops.js, frontend/src/Components/Charts/UseOfForce/UseOfForce.js
Update charts to use `VelocityTooltip` in favor of CopwatchChart tooltip. Since it's supported out of the box. 
Preview:
Issue
[Story 14244](https://app.shortcut.com/caktusgroup/story/14244/make-hover-display-less-intrusive)
=> Resolve: 14244 Make hover display less intrusive

frontend/src/Components/AgencyData/AgencyHeader.js, frontend/src/Components/Charts/Overview/Overview.js, frontend/src/Components/Charts/Searches/Searches.js, frontend/src/Components/Charts/TrafficStops/TrafficStops.js
Update spots where "department" is used for an officer page. 
Example: "stop from officer" was previously "stop from department"
Closes #12496
=> Resolve: 12496 Missing 'Officer' text

frontend/src/Components/Charts/ChartPrimitives/StackedBar.js, frontend/src/Components/Charts/TrafficStops/TrafficStops.js
Wrapping the `StackedBar` in a component using `VictoryVoronoiContainer` caused the site to crash when you remove an ethnicity from the "TRAFFIC STOPS BY PERCENTAGE" chart. 
The `VictoryVoronoiContainer` is needed to display labels for line charts.
Also cleaned up a bit of logic, there were lingering api calls that caused me some confusion to its purpose.
=> Resolve: 14044 Graph performance issues

frontend/src/Components/Charts/UseOfForce/UseOfForce.js
- Update wording for officer pages in use of force chart
Preview:
Closes #14909
=> Resolve: 14909 Change plural officers subtext on Use Of Force page to indicate the singular officer it shows data for

frontend/src/Components/Charts/ChartPrimitives/GroupedBar.js, frontend/src/Components/Charts/SearchRate/SearchRate.js
- Add several `VictoryTooltip` props to fix the tooltip being cropped under the left side navigation when view a bar on the left side of the graph . 
Preview:
Closes #15707
=> Resolve: 15707 Fix tooltip cropped in search rate graph

frontend/src/Components/Charts/ChartSections/EmptyChartMessage.js
- Improve logic of checking if graphs have valid data
Preview: (Previously Searches did not show the Empty Data alert banner)
Closes #15789
=> Resolve: 15789 Add the no data graphic to the "searches" page when no data is available

frontend/src/Components/Charts/Overview/Overview.js
- The links under the pie charts in `Overview.js` component were broken for officers. 
- Add `buildUrl` function to correctly build url if officer id is available. 
Closes #15806
=> Resolve: 15806 Fix overview links

frontend/src/Components/Charts/Contraband/Contraband.js, frontend/src/Components/Charts/SearchRate/SearchRate.js, frontend/src/Components/Charts/Searches/Searches.js, frontend/src/Components/Charts/TrafficStops/TrafficStops.js, frontend/src/Components/Charts/UseOfForce/UseOfForce.js, frontend/src/Components/Charts/chartUtils.js, frontend/src/Components/Elements/Table/TableModal.js
- Add chartUtil method: `reduceEthnicityByYears` to consolidate ethnicity date by year
- Add `Total` column to view row totals.
- Add option to consolidate data, split by traffic stop type, search type, etc. to view year totals faster than having to manually calculate. 
Preview:
=> Resolve: Consolidate table rows by year and add totals

frontend/src/Components/Charts/Contraband/Contraband.js, frontend/src/Components/Charts/SearchRate/SearchRate.js, frontend/src/Components/Charts/Searches/Searches.js, frontend/src/Components/Charts/TrafficStops/TrafficStops.js, frontend/src/Components/Charts/UseOfForce/UseOfForce.js, frontend/src/Components/Charts/chartUtils.js, frontend/src/Components/Elements/Table/TableModal.js
- Previously the row total would be calculated on the fly by react-table which prevented the count from showing up in the csv download. 
- Now, we manually calculate the total as before, but also the download has the totals as well. 
Preview:
Closes #16211
=> Resolve: 16211 Consolidated Year Total is missing from exports

frontend/src/Components/AgencyData/AgencyData.js, frontend/src/Components/AgencyData/AgencyData.styled.js, frontend/src/Components/Charts/ChartSections/ChartPageBase.styled.js, frontend/src/Components/Charts/TrafficStops/TrafficStops.js, frontend/src/Components/Charts/UseOfForce/UseOfForce.js, frontend/src/Components/Sidebar/Sidebar.js, frontend/src/Components/Sidebar/Sidebar.styled.js
- When the compare agencies features was merged. The left side of the graphs were harder to read than the left. 
- With these changes, we simply move the sidebar to the top of the left view to increase the width and hopefully make it easier to read the data from. 
Preview:
Closes #16208
=> Resolve: 16208 Graph rendering cropped out of view for certain data sets

frontend/src/Components/Header/Header.styled.js
Fixed issue FJ-107: https://app.clickup.com/t/3zy0n88
Found that setting the min and max height for the header file fixed this issue. The problem was because the the AgencyHeader and ChartPageBase would be too tall and squeeze the height out of the header. Setting the min-height seemed to fix the problem but I also set the max-height so that the padding looked correct. 
I used rem units to avoid the padding issues from occurring when changing the zoom resolution on the window as we..
=> Fixed changing height in header

frontend/src/Components/Charts/SearchRate/SearchRate.js
The white checkbox had no effect on updating the Search Rate graph.
=> Hide white checkbox for Search Rate

frontend/src/Components/Charts/ChartRoutes.js, frontend/src/Components/Charts/Overview/Overview.js
There wasn't a way to filter the overview page by year to compare same agency against itself for a different year.
=> Allow filtering of year in overview subpage

frontend/src/Components/Charts/chartUtils.js
- When consolidating years, some agencies might not be up to date and crashed the app.
=> Only show years that are available

frontend/src/Components/App.js, frontend/src/Components/Elements/Table/TableModal.js, frontend/src/Components/Header/Header.styled.js, frontend/src/Components/Layout.styled.js
- On mobile, the header took up too much space when scrolling. 
- Like the footer, keep the header at the top of the page and not pin the position to the top when scrolling.
=> Remove fixed header

frontend/src/Components/AgencyData/AgencyData.js, frontend/src/Components/Elements/Alert/Alert.js, frontend/src/Components/Elements/Alert/Alert.styled.js
- Add `Alert` component
- Add `CompareAlertBox` component that only shows when device is in portrait mode and is comparing agencies. 
Preview:
=> Add alert box for bad device orientation when comparing departments

.pre-commit-config.yaml, deploy/group_vars/all.yml, deploy/requirements.yml
- https://app.clickup.com/t/8677fzttd
```
❯ inv deploy.install
❯ inv deploy.playbook -n deploy-cluster.yml
❯ kubectl -n kube-system get cronjob
NAME          SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
descheduler   */2 * * * *   False     0        59s             6m11s
```
```
❯ inv deploy.playbook -n deploy-cluster.yml
❯ kubectl -n ingress-nginx get pod -o wide 
NAME                                        READY   STATUS    RESTARTS   AGE     IP            NODE                                        NOMINATED NODE   READINESS GATES
ingress-nginx-controller-7b454df556-ds79n   1/1     Running   0          2m17s   10.0.15.220   ip-10-0-14-203.us-east-2.compute.internal   <none>           <none>
ingress-nginx-controller-7b454df556-z4hl7   1/1     Running   0          117s …
```
=> Deploy descheduler, upgrade Helm charts 

tsdata/sql.py
Add `IF EXISTS` drop `DROP INDEX` statements during import.
- https://app.clickup.com/t/8677ja8mt
```python
from django.db import connections
from tsdata.sql import drop_constraints_and_indexes, get_sql_statements, SELECT_DROP_CONSTRAINTS_SQL, SELECT_DROP_INDEXES_SQL
with connections["traffic_stops_nc"].cursor() as cursor:
sql = get_sql_statements(cursor, SELECT_DROP_CONSTRAINTS_SQL)
sql += get_sql_statements(cursor, SELECT_DROP_INDEXES_SQL)
print(sql)
```
Generates two DROP statements, so the 2nd one fails:
```sql
-- ...
ALTER TABLE "public"."nc_resource_agencies" DROP CONSTRAINT IF EXISTS "nc_resource_agencies_resource_id_agency_id_2d682e8a_uniq";
-- ...
DROP INDEX "public"."nc_resource_agencies_resource_id_agency_id_2d682e8a_uniq" RESTRICT;
-- ...
```
Perhaps this type of constraint is …
=> Only drop index IF EXISTS during import

nc/admin.py, nc/views.py
A bug in staging prevents the resources from updated the list of agencies associated per tag.
- Don't cache the list of resources
- Clear and set the agencies per resource change on save
=> Do not cache resources + save related fields for resources

nc/admin.py, nc/models.py, nc/views.py
Suggested enhancements to #187:
* Reduced size of materialized view by ~13.5m rows
* Add multicolumn index on ("agency", "date") to optimize date filtering with Parallel Index Scans
```sh
./migrate_all_dbs.sh
python manage.py refresh_pgviews --database=traffic_stops_nc
```
Before:
```sql
traffic_stops_nc=# SELECT count(*) FROM nc_stopsummary;
count   
----------
22864268
(1 row)
```
After:
```sql
traffic_stops_nc=# SELECT count(*) FROM nc_stopsummary;
count  
---------
9429402
(1 row)
```
Savings:
```sql
\pset numericlocale
traffic_stops_nc=# SELECT 22864268-9429402 AS removed_rows;
removed_rows 
--------------
13,434,866
```
Add multicolumn index on ("agency", "date") to optimize date filtering with Parallel Index Scans:
```sql
traffic_stops_nc=# EXPLAIN ANALYZE SELECT …
```
=> Truncate materialized view to month

frontend/package-lock.json, frontend/package.json, frontend/src/Components/AboutPage/AboutPage.js, frontend/src/Components/AgencyData/AgencyHeader.js, frontend/src/Components/AgencyData/AgencyHeader.styled.js
Ticket:
- https://app.clickup.com/t/863gean72
- Adds `popper-js` package for tooltips (using in later tickets as well)
- Update about page to include source of census
=> Add popper-js for tooltips

nc/views.py
- Update `QueryKeyConstructor` to include `from` and `to` params to update cached responses.
=> Add from/to to list of cache params

nc/admin.py
Ticket:
- https://app.clickup.com/t/863g8xz5j 
Changes:
- Adds `created_date` to resource detail page
Preview:
=> Add resource created date as readonly field in resource detail page

Makefile, frontend/src/Components/Charts/SearchRate/SearchRate.js, frontend/src/Components/Charts/SearchRate/SearchRate.styled.js, frontend/src/util/tooltipLanguage.js
Ticket:
- https://app.clickup.com/t/863gea6f1
Changes:
- Add a util function to return correct copy for each stop purpose
- Add a popperjs tooltip to render above each stop purpose when hovering
- Add convenient make command to refresh stop summary 
Preview:
=> Add tooltips to the data labels for Search Rate graph

frontend/src/Components/AgencyData/AgencyHeader.styled.js
Ticket:
- https://app.clickup.com/t/863gean72
Changes:
- Add some indication that the census title is clickable, dotted underline and pointed cursor
Preview:
=> Add underline for census link

Dockerfile, deploy/group_vars/all.yml, deploy/requirements.yml, requirements/base/base.in, requirements/base/base.txt, requirements/deploy/deploy.in, requirements/deploy/deploy.txt, requirements/dev/dev.in, requirements/dev/dev.txt
Closes:
- https://app.clickup.com/t/86774uj0w
Performs Kubernetes upgrades in the traffic stops cluster. Updates the following:
Kubernetes and Nodes -> `1.25`
Kubectl -> `1.25.10`
Helm -> `3.12.0`
Descheduler -> `0.25`
Ansible requirements
Other minor package dependencies
=> Kubernetes upgrades to v1.25

frontend/src/Components/Charts/TrafficStops/TrafficStops.js, frontend/src/Components/Charts/TrafficStops/TrafficStops.styled.js
Ticket:
- https://app.clickup.com/t/8684x8egn
- Adds checkboxes to toggle which grouped by stop purpose graphs user wants to see at a time. 
Preview:
=> Add toggle for traffic grouped stop purpose graphs

frontend/package-lock.json, frontend/package.json, frontend/src/Components/App.js, frontend/src/Components/Charts/ChartSections/ChartsCommon.styled.js, frontend/src/Components/Charts/ChartSections/Legend/Legend.styled.js, frontend/src/Components/Charts/TrafficStops/TrafficStops.js, frontend/src/Components/Charts/TrafficStops/TrafficStops.styled.js, frontend/src/Components/Elements/Dropdown/Dropdown.js, frontend/src/Components/Elements/Inputs/Checkbox.js, frontend/src/Components/Elements/Inputs/Checkbox.styled.js, frontend/src/Components/NewCharts/PieChart.js, frontend/src/img/icons/CheckboxIcon.js
Ticket:
- https://app.clickup.com/t/86853kxv8
- https://app.clickup.com/t/86853ndzp
- Adds switcher to toggle between line graphs and pie charts for the grouped by stop purpose traffic stops graph.
Preview:
=> Add pie charts for grouped by stop purpose

frontend/src/Components/Charts/TrafficStops/TrafficStops.js, frontend/src/Components/Charts/TrafficStops/TrafficStops.styled.js, frontend/src/Components/Charts/UseOfForce/UseOfForce.js, frontend/src/Components/Elements/MonthRangePicker.js, frontend/src/Components/NewCharts/LineChart.js, nc/urls.py, nc/views.py
Tickets:
- https://app.clickup.com/t/868580qgz
- https://app.clickup.com/t/868580eqa
- Swaps out the traffic stops by count graph to the new chartjs line chart, further simplifying the logic + code
- Adds separate view in backend to return data only for traffic stops by count
- Removed dead code on the frontend
Preview:
=> Swap traffic stops by count using new charts

frontend/src/Components/Elements/Table/TableModal.js
- Should fix the weird table data when filtering graphs by stop purpose
=> Fix table modal filtering bugs

nc/prime_cache.py, nc/urls.py
- Add the new traffic stops api endpoints to the list of urls the backend uses to cache the expensive views for the frontend graphs
=> Expand list of urls for prime caching

Dockerfile
What's change:
- Node16 is ending support soon https://nodejs.org/en/blog/announcements/nodejs16-eol
- Node18 has maintenance support until April 2025
=> Upgrade node version to 18

frontend/src/Components/Charts/ChartSections/ChartPageBase.styled.js
- Update how the content is displayed for chart pages, expanding the page to fill the remaining white space under the footer to keep it consistent with the other compared agency page.
=> Fix footer not pinned to bottom of screen when comparing agencies

frontend/src/Components/Charts/Contraband/Contraband.js, frontend/src/Components/Charts/TrafficStops/TrafficStops.js, nc/views.py
=> Update pie and bar colors to their hovered versions

frontend/src/Components/Charts/UseOfForce/UseOfForce.js, frontend/src/Components/NewCharts/VerticalBarChart.js, nc/prime_cache.py, nc/urls.py, nc/views.py
- Added new view to return data for use of force graph formatted for the new library
- Update UseOfForce.js to use new library + rearrange layout to maximize screen width to view data easily.
=> Update Use of Force graph to use new library

frontend/src/Components/Charts/TrafficStops/TrafficStops.js, frontend/src/Components/Charts/chartUtils.js, frontend/src/Components/NewCharts/VerticalBarChart.js, nc/prime_cache.py, nc/urls.py, nc/views.py
- Add api view for Traffic Stops By Percentage
- Update stops by percentage graph to use new library + fetch data from new api
=> Convert stops by percentage to new graph library

frontend/src/Components/Charts/Contraband/Contraband.js, nc/views.py
- Match traffic stops by stop purpose graph colors to the contraband percentages by stop purpose
- Update wording of contraband modal subheading to correctly match description of data -> percentage to integers
=> Update traffic stop colors and contraband table modal wording

nc/urls.py
Reason: Statewide agency id is negative and would be redirected, crashing the contraband page
=> Remove int path converter for all urls

frontend/src/Components/Charts/Contraband/Contraband.js
- Move a single year dropdown to the top of the charts and have it update all the graphs simultaneously
- Update contraband table modal heading text to reflect counts and not percentages 
Preview:
=> Consolidate Contraband year dropdowns

nc/data/importer.py, nc/models.py, nc/views.py
- Use drf's `cache_page` method decorator instead of drf extensions `cache_response` since it's not been maintained in a while and is crashing the backend.
- Update the summary views to inherit the caching mixin
- Update the import to prime the cache when data is being imported nightly
=> Add support for caching api/mat views.

nc/views.py
- Updated `AgencySearchRateView` to update the searches/stops dataframe using floats for `0` if no stop purpose was found for a race
- Fix possible zero division error for averages column
=> Fix Search Rate invalid JSON data bug

frontend/src/Components/AgencyData/AgencyData.js, frontend/src/Components/Charts/Arrest/Arrests.js, frontend/src/Components/Charts/Arrest/Arrests.styles.js, frontend/src/Components/Charts/Arrest/Charts/ArrestsByPercentage.js, frontend/src/Components/Charts/Arrest/Charts/CountOfStopsAndArrests.js, frontend/src/Components/Charts/Arrest/Charts/PercentageOfSearches.js, frontend/src/Components/Charts/Arrest/Charts/PercentageOfSearchesForPurposeGroup.js, frontend/src/Components/Charts/Arrest/Charts/PercentageOfSearchesPerStopPurpose.js, frontend/src/Components/Charts/Arrest/Charts/PercentageOfStops.js, frontend/src/Components/Charts/Arrest/Charts/PercentageOfStopsForPurposeGroup.js, frontend/src/Components/Charts/Arrest/Charts/PercentageOfStopsPerContrabandType.js, frontend/src/Components/Charts/Arrest/Charts/PercentageOfStopsPerStopPurpose.js, frontend/src/Components/Charts/ChartRoutes.js, frontend/src/Components/NewCharts/HorizontalBarChart.js, frontend/src/Components/Sidebar/Sidebar.js, frontend/src/Routes/slugs.js, nc/models.py, nc/prime_cache.py, nc/urls.py, nc/views.py
**Branched off #285**
- Added chart + api views to display percentage of stops with arrests per contraband type.
Preview:
=> Add arrests percentage stops by contraband type graph

frontend/src/Components/Charts/Arrest/Charts/CountOfStopsAndArrests.js, frontend/src/Components/Charts/Arrest/Charts/PercentageOfSearches.js, frontend/src/Components/Charts/Arrest/Charts/PercentageOfSearchesForPurposeGroup.js, frontend/src/Components/Charts/Arrest/Charts/PercentageOfSearchesPerStopPurpose.js, frontend/src/Components/Charts/Arrest/Charts/PercentageOfStops.js, frontend/src/Components/Charts/Arrest/Charts/PercentageOfStopsForPurposeGroup.js, frontend/src/Components/Charts/Arrest/Charts/PercentageOfStopsPerContrabandType.js, frontend/src/Components/Charts/Arrest/Charts/PercentageOfStopsPerStopPurpose.js, frontend/src/Components/Charts/ChartSections/ChartsCommon.styled.js, frontend/src/Components/Charts/Contraband/Contraband.js, frontend/src/Components/Charts/Contraband/Contraband.styled.js, frontend/src/Components/Charts/SearchRate/SearchRate.js, frontend/src/Components/Charts/Searches/Searches.js, frontend/src/Components/Charts/TrafficStops/TrafficStops.js, frontend/src/Components/Charts/TrafficStops/TrafficStops.styled.js, frontend/src/Components/Charts/UseOfForce/UseOfForce.js, frontend/src/Components/NewCharts/HorizontalBarChart.js, frontend/src/Components/NewCharts/VerticalBarChart.js
Ticket:
- https://app.clickup.com/t/8686mb5nb
- Add a common `ChartContainer` so charts are responsive. This way its data is more accessible on mobile screens but keeping desktop experience as it was.
Preview:
=> Cleanup charts for mobile screens.

deploy/group_vars/k8s.yml
Let Kubernetes ensure only one beat process is running
=> Avoid setting celery beat PID file

frontend/src/Components/Charts/UseOfForce/UseOfForce.js
Ticket:
- https://app.clickup.com/t/86886ymb2
- Update the pie chart component to pass a false value for the maintainAspectRatio flag, preventing the chart from taking up too much space.
=> Fix Use of Force pie chart size

deploy/group_vars/all.yml
We were hitting the pod limit with medium nodes (17 per node), so upgrading to large nodes.
=> Switch to t3a.large k8s nodes

deploy/group_vars/all.yml
```
> helm -n newrelic list   
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
newrelic-bundle newrelic        5               2024-06-21 13:44:53.812967 -0400 EDT    deployed        nri-bundle-5.0.82                      
```
I ran the playbook (`inv playbook -n deploy-hosting-services.yml`) & made sure that the logs continued to go to New Relic. 
**Test**
1. Login to the New Relic (GP Cluster Account).
2. You can filter by `namespace_name: "ingress-nginx"`.
3. Go to a staging site of your choice, click around, and make sure that logs are still displaying as expected.
**Logs**
```
13:46:57.945
[pid: 15|app: 0|req: 6809/10274] 10.0.12.120 () {72 vars in 1554 bytes} [Fri Jun 21 13:46:57 2024] GET …
```
=> [CVE-2024-4323] Update New Relic Chart Version

requirements/base/base.in, requirements/base/base.txt, requirements/dev/dev.in, requirements/dev/dev.txt, requirements/test/test.txt
This PR attempts to fix the build by updating necessary packages. It appears that #299 and #302 broke the build and deploy. 
The build is failing for two reasons:
1. Since the app now uses Python 3.10 some of the package versions were deprecated: `celery`, `numpy`, `pandas`, etc. Thus this error is showing:
```
ERROR: Could not find a version that satisfies the requirement celery==4.4.6 (from versions: 0.1.2, 0.1.4, 0.1.6, 0.1.7, 0.1.8, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.2.0, 0.3.0, 0.3.7, 0.3.20, 0.4.0, 0.4.1, 0.6.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, …
```
=> Fix Build post K8s/Python Upgrade

Dockerfile, deploy/deploy-cluster.yml, deploy/group_vars/all.yml, deploy/group_vars/k8s.yml, deploy/inventory-cdn, deploy/requirements.yml, docs/deploy.rst, requirements/base/base.in, requirements/base/base.txt, requirements/deploy/deploy.txt, requirements/dev/dev.in, requirements/dev/dev.txt, requirements/test/test.txt
This PR serves as documentation/reference for the Kubernetes upgrade on the `trafficstops-stack-cluster` cluster. Currently the live site on this cluster are [nccopwatch](https://nccopwatch.org/) and [staging-nccopwatch.org](https://staging-nccopwatch.org/).
**Notes:**
- There was zero downtime during the upgrade.
**Ingress Nginx**
```
> helm -n ingress-nginx list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ingress-nginx   ingress-nginx   9               2025-01-02 10:00:46.759808 -0500 EST    deployed        ingress-nginx-4.11.3    1.11.3
```
**Cert Manager**
```
> helm -n cert-manager list 
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS …
```
=> Kubernetes Upgrade v1.29 to v1.30 

.github/workflows/test.yaml, Dockerfile, deploy/group_vars/all.yml, deploy/stack/eks-no-nat.yml, docker-compose.deploy.yml, docker-compose.yml, docs/dev-setup.rst
This PR updates the client version of Postgres from v12 to v15. Postgres 12 reached EOL on **Nov 14, 2024**. 
Closes:
- https://app.clickup.com/t/868b4qh6g
=> Upgrade Postgres v12 to v16

Dockerfile
This PR sets `UWSGI_MAX_REQUESTS` to 1000, reloading workers to avoid memory leaks.
Closes: 
- https://app.clickup.com/t/868ct6u4w
=> UWSGI Max Reqquests

.github/workflows/deploy.yaml
This PR updates the Ubuntu version from deprecated `v20.04` to `latest`, ensuring the following error won't happen again. 
```
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15.
```
=> Update Ubuntu on Deploy Job

Dockerfile, deploy/group_vars/all.yml, deploy/requirements.yml, requirements/base/base.in, requirements/base/base.txt, requirements/dev/dev.in, requirements/dev/dev.txt
This PR updates requirements to work with K8s version `1.32.x`.
**Ingress Nginx**
```
> helm -n ingress-nginx list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ingress-nginx   ingress-nginx   11              2025-07-11 10:19:15.038463 -0400 EDT    deployed        ingress-nginx-4.12.3    1.12.3    
```
**Cert Manager**
```
> helm -n cert-manager list                      
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
cert-manager    cert-manager    10              2025-07-11 09:51:23.552681 -0400 EDT    deployed        cert-manager-v1.17.2    v1.17.2   
```
**New Relic**
```
> helm -n newrelic list
NAME …
```
=> Kubernetes Upgrade v1.30 to v1.32

nc/tests/api/test_arrests.py, nc/tests/api/test_stop_search_rate.py, nc/views/likelihood.py, nc/views/main.py, tasks.py
Return an empty ACS dataframe with correct columns if no ACS data is found.
* Visit http://localhost:3000/agencies/80/search-rate
* Choose 2025 in the year dropdown
* No exception in terminal
=> Prevent API error if no ACS data exists for query
